name: Medschoolcoach
description: Medschoolcoach app

version: 1.4.24+3

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter : ">=1.17.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_size_and_fade: ^1.1.4
  yaml: 2.2.1
  json_annotation: 3.0.1
  enum_to_string : ^1.0.14
  intl: 0.16.1
  http: 0.12.0+4
  cupertino_icons: 0.1.3
  flutter_svg: 0.18.0
  flutter_i18n: 0.8.3
  flutter_secure_storage: 3.3.3
  firebase_performance:
  url_launcher: 5.4.2
  transparent_image: 1.0.0
  injector: 1.0.8
  pie_chart: 3.1.1
  flutter_animation_progress_bar : ^1.0.6
  flutter_slidable: 0.5.4
  fluttertoast: 4.0.1
  wakelock: 0.1.4+2
  webview_flutter:
  flutter_html:
  uni_links: ^0.4.0
  native_mixpanel:
  srt_parser: ^1.1.0+5
  firebase_core:
  firebase_crashlytics:
  firebase_analytics:
  flushbar: ^1.10.4
  cached_network_image:
  carousel_slider: ^2.3.1
  chewie: 0.9.10
  flutter_appauth:
  auto_size_text: ^2.1.0
  shake: ^0.1.0
  syncfusion_flutter_datepicker:
  vector_math: ^2.0.8
  percent_indicator: "^2.1.7+2"
  visibility_detector: ^0.1.5
  flutter_local_notifications:
  rxdart: ^0.23.1
  device_preview:

dependency_overrides:
  video_player:
    git:
      url: https://github.com/MedSchoolCoach/plugins.git
      path: packages/video_player
      ref: always-speed
  csslib: ^0.16.2

dev_dependencies:
  build_runner: 1.7.3
  json_serializable: 3.3.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/svg/
    - assets/i18n/en_US.yaml
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
