name: Medschoolcoach
description: Medschoolcoach app

version: 1.4.25+33

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter : ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_size_and_fade: ^2.0.0
  yaml: 3.1.0
  json_annotation: ^4.0.1
  enum_to_string: ^2.0.1
  intl: ^0.17.0
  ndialog: ^4.1.0
  data_connection_checker: ^0.3.4
  http: ^0.13.3
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  mixpanel_flutter: ^1.1.0
  device_preview: ^0.7.3
  flutter_i18n: ^0.22.3
  flutter_secure_storage: ^4.2.0
  firebase_performance:
  firebase_messaging: ^10.0.0
  url_launcher: ^6.0.4
  transparent_image: ^2.0.0
  injector: 1.0.8
  pie_chart: 5.0.0
  flutter_animation_progress_bar : ^2.0.0
  flutter_slidable: ^0.6.0
  fluttertoast: ^8.0.7
  wakelock: ^0.4.0
  localstorage: ^4.0.0+1
  webview_flutter:
  flutter_html:
  uni_links: ^0.5.1
  universal_io: ^2.0.4
  srt_parser: ^1.1.0+5
  firebase_core:
  firebase_crashlytics:
  firebase_analytics: ^8.1.0
  flushbar: ^1.10.4
  cached_network_image:
  carousel_slider: ^3.0.0
  quiver: ^3.0.1
  chewie: ^1.0.0
  flutter_appauth:
  auto_size_text: ^2.1.0
  shake: ^1.0.0
  syncfusion_flutter_datepicker:
  vector_math: ^2.0.8
  percent_indicator: ^3.0.1
  visibility_detector: ^0.2.0
  flutter_local_notifications:
  crypto: ^3.0.0
  rxdart: ^0.27.0

dependency_overrides:
  video_player:
    git:
      url: https://github.com/MedSchoolCoach/plugins.git
      path: packages/video_player
      ref: always-speed
  csslib: ^0.16.2

dev_dependencies:
  build_runner: ^2.0.3
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/svg/
    - assets/i18n/en_US.yaml
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
