name: Medschoolcoach
description: Medschoolcoach app

version: 1.4.12

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  yaml: 2.2.1
  json_annotation: 3.0.1
  intl: 0.16.1
  http: 0.12.0+4
  cupertino_icons: 0.1.3
  flutter_svg: 0.18.0
  flutter_i18n: 0.8.3
  flutter_secure_storage: 3.3.3
  firebase_performance: 0.3.2
  url_launcher: 5.4.2
  transparent_image: 1.0.0
  injector: 1.0.8
  video_player:
    git:
      url: https://github.com/MedSchoolCoach/plugins.git
      path: packages/video_player
      ref: always-speed
  pie_chart: 3.1.1
  flutter_slidable: 0.5.4
  fluttertoast: 4.0.1
  wakelock: 0.1.4+1
  flutter_html: ^0.11.1
  uni_links: ^0.4.0
  native_mixpanel: ^0.1.2
  srt_parser: ^1.1.0+5
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.1.4+1
  firebase_analytics: ^6.0.0
  flushbar: ^1.10.4
  cached_network_image: ^2.3.1


dev_dependencies:
  build_runner: 1.7.3
  json_serializable: 3.3.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/svg/
    - assets/i18n/en_US.yaml
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
